/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyYespRouteImport } from './routes/why-yesp'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as FrameworkRouteImport } from './routes/framework'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResearchIndexRouteImport } from './routes/research.index'
import { Route as ResearchHiddenCostOfOperationalReportingRouteImport } from './routes/research.hidden-cost-of-operational-reporting'
import { Route as ResearchAiReadinessFoundationGapRouteImport } from './routes/research.ai-readiness-foundation-gap'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogTheReportingTaxRouteImport } from './routes/blog.the-reporting-tax'
import { Route as BlogWhyAiProjectsFailRouteImport } from './routes/blog.why-ai-projects-fail'
import { Route as BlogFiveDigitalTransformationMistakesRouteImport } from './routes/blog.five-digital-transformation-mistakes'
import { Route as ApiOgRouteImport } from './routes/api/og'

const WhyYespRoute = WhyYespRouteImport.update({
  id: '/why-yesp',
  path: '/why-yesp',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const FrameworkRoute = FrameworkRouteImport.update({
  id: '/framework',
  path: '/framework',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchIndexRoute = ResearchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResearchRoute,
} as any)
const ResearchHiddenCostOfOperationalReportingRoute =
  ResearchHiddenCostOfOperationalReportingRouteImport.update({
    id: '/hidden-cost-of-operational-reporting',
    path: '/hidden-cost-of-operational-reporting',
    getParentRoute: () => ResearchRoute,
  } as any)
const ResearchAiReadinessFoundationGapRoute =
  ResearchAiReadinessFoundationGapRouteImport.update({
    id: '/ai-readiness-foundation-gap',
    path: '/ai-readiness-foundation-gap',
    getParentRoute: () => ResearchRoute,
  } as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogTheReportingTaxRoute = BlogTheReportingTaxRouteImport.update({
  id: '/the-reporting-tax',
  path: '/the-reporting-tax',
  getParentRoute: () => BlogRoute,
} as any)
const BlogWhyAiProjectsFailRoute = BlogWhyAiProjectsFailRouteImport.update({
  id: '/why-ai-projects-fail',
  path: '/why-ai-projects-fail',
  getParentRoute: () => BlogRoute,
} as any)
const BlogFiveDigitalTransformationMistakesRoute =
  BlogFiveDigitalTransformationMistakesRouteImport.update({
    id: '/five-digital-transformation-mistakes',
    path: '/five-digital-transformation-mistakes',
    getParentRoute: () => BlogRoute,
  } as any)
const ApiOgRoute = ApiOgRouteImport.update({
  id: '/api/og',
  path: '/api/og',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/framework': typeof FrameworkRoute
  '/industries': typeof IndustriesRoute
  '/research': typeof ResearchRouteWithChildren
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/why-yesp': typeof WhyYespRoute
  '/api/og': typeof ApiOgRoute
  '/blog/': typeof BlogIndexRoute
  '/blog/the-reporting-tax': typeof BlogTheReportingTaxRoute
  '/blog/why-ai-projects-fail': typeof BlogWhyAiProjectsFailRoute
  '/blog/five-digital-transformation-mistakes': typeof BlogFiveDigitalTransformationMistakesRoute
  '/research/ai-readiness-foundation-gap': typeof ResearchAiReadinessFoundationGapRoute
  '/research/hidden-cost-of-operational-reporting': typeof ResearchHiddenCostOfOperationalReportingRoute
  '/research/': typeof ResearchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/framework': typeof FrameworkRoute
  '/industries': typeof IndustriesRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/why-yesp': typeof WhyYespRoute
  '/api/og': typeof ApiOgRoute
  '/blog': typeof BlogIndexRoute
  '/blog/the-reporting-tax': typeof BlogTheReportingTaxRoute
  '/blog/why-ai-projects-fail': typeof BlogWhyAiProjectsFailRoute
  '/blog/five-digital-transformation-mistakes': typeof BlogFiveDigitalTransformationMistakesRoute
  '/research/ai-readiness-foundation-gap': typeof ResearchAiReadinessFoundationGapRoute
  '/research/hidden-cost-of-operational-reporting': typeof ResearchHiddenCostOfOperationalReportingRoute
  '/research': typeof ResearchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/framework': typeof FrameworkRoute
  '/industries': typeof IndustriesRoute
  '/research': typeof ResearchRouteWithChildren
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/why-yesp': typeof WhyYespRoute
  '/api/og': typeof ApiOgRoute
  '/blog/': typeof BlogIndexRoute
  '/blog/the-reporting-tax': typeof BlogTheReportingTaxRoute
  '/blog/why-ai-projects-fail': typeof BlogWhyAiProjectsFailRoute
  '/blog/five-digital-transformation-mistakes': typeof BlogFiveDigitalTransformationMistakesRoute
  '/research/ai-readiness-foundation-gap': typeof ResearchAiReadinessFoundationGapRoute
  '/research/hidden-cost-of-operational-reporting': typeof ResearchHiddenCostOfOperationalReportingRoute
  '/research/': typeof ResearchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessment'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/framework'
    | '/industries'
    | '/research'
    | '/services'
    | '/team'
    | '/why-yesp'
    | '/api/og'
    | '/blog/'
    | '/blog/the-reporting-tax'
    | '/blog/why-ai-projects-fail'
    | '/blog/five-digital-transformation-mistakes'
    | '/research/ai-readiness-foundation-gap'
    | '/research/hidden-cost-of-operational-reporting'
    | '/research/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessment'
    | '/careers'
    | '/contact'
    | '/framework'
    | '/industries'
    | '/services'
    | '/team'
    | '/why-yesp'
    | '/api/og'
    | '/blog'
    | '/blog/the-reporting-tax'
    | '/blog/why-ai-projects-fail'
    | '/blog/five-digital-transformation-mistakes'
    | '/research/ai-readiness-foundation-gap'
    | '/research/hidden-cost-of-operational-reporting'
    | '/research'
  id:
    | '__root__'
    | '/'
    | '/assessment'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/framework'
    | '/industries'
    | '/research'
    | '/services'
    | '/team'
    | '/why-yesp'
    | '/api/og'
    | '/blog/'
    | '/blog/the-reporting-tax'
    | '/blog/why-ai-projects-fail'
    | '/blog/five-digital-transformation-mistakes'
    | '/research/ai-readiness-foundation-gap'
    | '/research/hidden-cost-of-operational-reporting'
    | '/research/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessmentRoute: typeof AssessmentRoute
  BlogRoute: typeof BlogRouteWithChildren
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  FrameworkRoute: typeof FrameworkRoute
  IndustriesRoute: typeof IndustriesRoute
  ResearchRoute: typeof ResearchRouteWithChildren
  ServicesRoute: typeof ServicesRoute
  TeamRoute: typeof TeamRoute
  WhyYespRoute: typeof WhyYespRoute
  ApiOgRoute: typeof ApiOgRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-yesp': {
      id: '/why-yesp'
      path: '/why-yesp'
      fullPath: '/why-yesp'
      preLoaderRoute: typeof WhyYespRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/framework': {
      id: '/framework'
      path: '/framework'
      fullPath: '/framework'
      preLoaderRoute: typeof FrameworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/the-reporting-tax': {
      id: '/blog/the-reporting-tax'
      path: '/the-reporting-tax'
      fullPath: '/blog/the-reporting-tax'
      preLoaderRoute: typeof BlogTheReportingTaxRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/why-ai-projects-fail': {
      id: '/blog/why-ai-projects-fail'
      path: '/why-ai-projects-fail'
      fullPath: '/blog/why-ai-projects-fail'
      preLoaderRoute: typeof BlogWhyAiProjectsFailRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/five-digital-transformation-mistakes': {
      id: '/blog/five-digital-transformation-mistakes'
      path: '/five-digital-transformation-mistakes'
      fullPath: '/blog/five-digital-transformation-mistakes'
      preLoaderRoute: typeof BlogFiveDigitalTransformationMistakesRouteImport
      parentRoute: typeof BlogRoute
    }
    '/research/': {
      id: '/research/'
      path: '/'
      fullPath: '/research/'
      preLoaderRoute: typeof ResearchIndexRouteImport
      parentRoute: typeof ResearchRoute
    }
    '/research/hidden-cost-of-operational-reporting': {
      id: '/research/hidden-cost-of-operational-reporting'
      path: '/hidden-cost-of-operational-reporting'
      fullPath: '/research/hidden-cost-of-operational-reporting'
      preLoaderRoute: typeof ResearchHiddenCostOfOperationalReportingRouteImport
      parentRoute: typeof ResearchRoute
    }
    '/research/ai-readiness-foundation-gap': {
      id: '/research/ai-readiness-foundation-gap'
      path: '/ai-readiness-foundation-gap'
      fullPath: '/research/ai-readiness-foundation-gap'
      preLoaderRoute: typeof ResearchAiReadinessFoundationGapRouteImport
      parentRoute: typeof ResearchRoute
    }
    '/api/og': {
      id: '/api/og'
      path: '/api/og'
      fullPath: '/api/og'
      preLoaderRoute: typeof ApiOgRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogIndexRoute: typeof BlogIndexRoute
  BlogTheReportingTaxRoute: typeof BlogTheReportingTaxRoute
  BlogWhyAiProjectsFailRoute: typeof BlogWhyAiProjectsFailRoute
  BlogFiveDigitalTransformationMistakesRoute: typeof BlogFiveDigitalTransformationMistakesRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogIndexRoute: BlogIndexRoute,
  BlogTheReportingTaxRoute: BlogTheReportingTaxRoute,
  BlogWhyAiProjectsFailRoute: BlogWhyAiProjectsFailRoute,
  BlogFiveDigitalTransformationMistakesRoute: BlogFiveDigitalTransformationMistakesRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ResearchRouteChildren {
  ResearchAiReadinessFoundationGapRoute: typeof ResearchAiReadinessFoundationGapRoute
  ResearchHiddenCostOfOperationalReportingRoute: typeof ResearchHiddenCostOfOperationalReportingRoute
  ResearchIndexRoute: typeof ResearchIndexRoute
}

const ResearchRouteChildren: ResearchRouteChildren = {
  ResearchAiReadinessFoundationGapRoute: ResearchAiReadinessFoundationGapRoute,
  ResearchHiddenCostOfOperationalReportingRoute:
    ResearchHiddenCostOfOperationalReportingRoute,
  ResearchIndexRoute: ResearchIndexRoute,
}

const ResearchRouteWithChildren = ResearchRoute._addFileChildren(
  ResearchRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessmentRoute: AssessmentRoute,
  BlogRoute: BlogRouteWithChildren,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  FrameworkRoute: FrameworkRoute,
  IndustriesRoute: IndustriesRoute,
  ResearchRoute: ResearchRouteWithChildren,
  ServicesRoute: ServicesRoute,
  TeamRoute: TeamRoute,
  WhyYespRoute: WhyYespRoute,
  ApiOgRoute: ApiOgRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
